export default () => ({
    port: parseInt(process.env.PORT, 10) || 3000,
    database: { mongoUri: process.env.MONGO_URI },
    jwt: {
        accessSecret: process.env.JWT_ACCESS_SECRET,
        refreshSecret: process.env.JWT_REFRESH_SECRET,
        accessExpires: process.env.ACCESS_TOKEN_EXPIRES || '15m',
        refreshExpires: process.env.REFRESH_TOKEN_EXPIRES || '7d',
    },
    bcryptSaltRounds: parseInt(process.env.BCRYPT_SALT_ROUNDS, 10) || 10,
    defaultAvatarUrl: process.env.DEFAULT_AVATAR_URL,
    smtp: {
        host: process.env.SMTP_HOST,
        port: parseInt(process.env.SMTP_PORT, 10) || 587,
        secure: process.env.SMTP_SECURE === 'true',
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
        from: process.env.SMTP_FROM,
    },
    throttle: {
        ttl: parseInt(process.env.THROTTLE_TTL, 10) || 60,
        limit: parseInt(process.env.THROTTLE_LIMIT, 10) || 10,
        login: { limit: parseInt(process.env.THROTTLE_LOGIN_LIMIT, 10) || 5, ttl: parseInt(process.env.THROTTLE_LOGIN_TTL, 10) || 900 },
        register: { limit: parseInt(process.env.THROTTLE_REGISTER_LIMIT, 10) || 3, ttl: parseInt(process.env.THROTTLE_REGISTER_TTL, 10) || 3600 },
    },
    emailVerification: {
        expiresMinutes: parseInt(process.env.EMAIL_VERIFICATION_EXPIRES_MINUTES, 10) || 15,
        required: process.env.EMAIL_VERIFICATION_REQUIRED === 'true',
    },
    pagination: { defaultLimit: parseInt(process.env.DEFAULT_PAGE_LIMIT, 10) || 20, maxLimit: parseInt(process.env.MAX_PAGE_LIMIT, 10) || 100 },
    loginHistory: { limit: parseInt(process.env.LOGIN_HISTORY_LIMIT, 10) || 10, notifyNewDevice: process.env.SUSPICIOUS_LOGIN_NOTIFICATION === 'true' },
    avatar: {
        tempDir: process.env.AVATAR_UPLOAD_TEMP || './uploads/temp',
        finalDir: process.env.AVATAR_FINAL_DIR || './uploads/avatars',
        maxSizeMb: parseInt(process.env.AVATAR_MAX_SIZE_MB, 10) || 5,
        allowedMimes: process.env.AVATAR_ALLOWED_MIMES?.split(',') || ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
        maxDimension: parseInt(process.env.AVATAR_MAX_DIMENSION, 10) || 1024,
        thumbDimension: parseInt(process.env.AVATAR_THUMB_DIMENSION, 10) || 200,
    },
    accountLock: {
        tempAttempts: parseInt(process.env.MAX_LOGIN_ATTEMPTS_TEMP, 10) || 5,
        permAttempts: parseInt(process.env.MAX_LOGIN_ATTEMPTS_PERM, 10) || 10,
        tempLockMinutes: parseInt(process.env.TEMP_LOCK_MINUTES, 10) || 15,
    },
    gracefulShutdownTimeout: parseInt(process.env.GRACEFUL_SHUTDOWN_TIMEOUT_MS, 10) || 10000,
    defaultUserRole: process.env.DEFAULT_USER_ROLE || 'user',
    superAdmin: { email: process.env.SUPER_ADMIN_EMAIL, password: process.env.SUPER_ADMIN_PASSWORD },
    redis: { host: process.env.REDIS_HOST, port: parseInt(process.env.REDIS_PORT, 10) || 6379, password: process.env.REDIS_PASSWORD },
});